### ISSUE TITLE
Where is the NETWORK config? 

### ISSUE THREAD

**Issue by jeanbapt** [deltaDAO/nautilus-examples#7]
# network config and pricing file missing

We are supposed to import NETWORK from ./config : no such file?

```ts
import { Network, NETWORK_CONFIGS, PRICING_CONFIGS } from './config'
```

I get this when doing npm start

```bash
Your selected NETWORK is PONTUSX
Creating new Nautilus instance with signer 0xD7783c77A0bd22914872BEbdFa1c00204fF9Ec50
No config found for given network '32456'
No default config found for given chainId
```

##Question on Faucet for Pontus-X

Also can you help on how to get faucet Euroe on Pontus-X?
Should I go with ethers , ABI etc. all the way or have you a helper ?
Not documented in the EuroE repo. 

Thank you for your help.

**Comment by jeanbapt** [comment]
I found the information, I'll try to set up the file in the nautilus project. 
[networksMetadata.config.js](config.ts)

**Comment by jeanbapt** [comment]
ok solved copy/pasted config.ts in the project.

**Comment by jeanbapt** [comment]
Still a pesky issue, also in nautilus-examples. 

```bash
No config found for given network '32456'
```

**Comment by Abrom8** [comment]
`No config found for given network '32456'` is not a problem. It's only indicating that it's a custom network and not included in the `ocean.js` included default configs. 

You will need a manual onboarding to Pontus-X devnet to receive tokens (there is no faucet yet). Feel free to contact us using contact@delta-dao.com .

**Comment by jeanbapt** [comment]
Thank you. Will do.
